email = "josue@hotmail.com"
password = "Josue123"
around_link = "https://around-v1.nm.tripleten-services.com/signin?lng=es"
avatar_url = "https://practicum-content.s3.us-west-1.amazonaws.com/new-markets/qa-sprint-7/avatarSelenium.png"
picture_url = "https://practicum-content.s3.us-west-1.amazonaws.com/new-markets/qa-sprint-7/photoSelenium.jpg"